server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/brain_boost
    username: postgres
    password: admin #if you need, please, replace username and password locally but do not push them
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations:
      - classpath:migrations